### PR TITLE
Add series of images to the sidebar.

### PR DESCRIPTION
**Pull request by dmark**
Add a series of images to the sidebar.

This is my first real pull request, so helpful tips and "take a hike amateur" are all appreciated. Let me know what I can do better. I cloned the source repo and pulled it down to my machine, made a branch, made my changes on the branch, pushed the branch back to my cloned repo and then created the pull request. Wasn't sure if I should have merged the branch with my master first.

Adds a series of images specified in SIDEBAR_IMAGES to the sidebar. The code is mostly a cut and paste of links.html and aboutme.html. I originally set this up to stick Amazon Web Services certification PNGs in my sidebar. Looks like:

screenshot_2015-05-20_15-59-33

### CODE REVIEW

**Comment by DandyDev** [comment]
Thanks for the PR! I added a couple of tips to the code. Maybe you could update your PR with those?

**Comment by dmark** [comment]
Will do. Thanks for the feedback. Do we close this one and I create a new one once my changes are made?

**Comment by DandyDev** [comment]
Nope, as long as you add the changes to the branch you already had, they will automatically be included in this current PR.
BTW, your PR is much better than a lot of stuff from open source "veterans" I come across, so you're doing great :)

**Comment by dmark** [comment]
Thanks again. Made your suggested changes and pushed it to the new branch. I think I did that right.

**Comment by DandyDev** [comment]
Done :) You can now throw away your feature branch in your own fork.

**Comment by cranmer** [comment]
interesting to watch open source in progress

**Comment by dmark** [comment]
Sweet. Thanks!

**Pull request merged**
