### PR TITLE
Add Heise Shariff support

### PR DESCRIPTION
**Pull request by krid78**
This patch add support for the c't Shariff-Project to offer privacy enabled social media buttons. For more information, see [Shariff on GitHub](https://github.com/heiseonline/shariff). You may refer to [my web-site](http://www.die-kriestens.de) as an example.

### CODE REVIEW

**Comment by DandyDev** [comment]
Hi Daniel! Thanks for your contribution. I'd love to merge this, but could you please move the javascript tag from the base.html into the article.html, in the script block there? See this commit on how I did this for AddThis as well: https://github.com/DandyDev/pelican-bootstrap3/commit/b37323a0e7ddc1bda70a9bd8482ec09b024dbb51 That way the javascript only gets loaded when the template requires it :)

**Comment by krid78** [comment]
Ok, I’ll try if this works on the weekend.

Regards,
	Daniel

> Am 10.02.2015 um 20:56 schrieb Daan Debie <notifications@github.com>:
> 
> Hi Daniel! Thanks for your contribution. I'd love to merge this, but could you please move the javascript tag from the base.html into the article.html, in the script block there? See this commit on how I did this for AddThis as well: b37323a That way the javascript only gets loaded when the template requires it :)
> 
> —
> Reply to this email directly or view it on GitHub.


--
Daniel Kriesten
daniel@die-kriestens.de
http://www.die-kriestens.de

**Comment by krid78** [comment]
I moved the code accordingly and updated shariff to v1.7.3. As far as I can see on my own site, the code is working and therefore ready to be merged :blush:

**Comment by DandyDev** [comment]
Great! Merged :)

**Pull request merged**
