### PR TITLE
Update Font Awesome and fix instagram/500px icons

### PR DESCRIPTION
**Pull request by iksaif**
Wanted to make 500px and instagram icons work correctly for SOCIAL links, this pull request should be able to fix that.

### CODE REVIEW

**Comment by lgiordani** [comment]
@iksaif If you are interested this feature has been merged into the laces3 theme https://github.com/lgiordani/laces3

**Comment by DandyDev** [comment]
@lgiordani I know I haven't been the quickest to respond to PRs lately (busy life, busy work), but you're now basically going over every PR in my project, trying to pull people to your project. That's not really nice form, don't you think?

**Comment by cranmer** [comment]
I'm not a seasoned contributor to open source projects where the contributors aren't already organized through some other means, so I don't know the etiquette in a situation like this. 

Could you join forces? As a user of the theme development has been a little slow (totally understandable, I'm busy too)... but I also I don't like the idea of it splitting the project or migrating to a different theme.

**Comment by lgiordani** [comment]
No no, sorry. As specified in the project I just wanted a bleeding edge version of the theme, and wanted only to notify people that, if they want, they have the feature there. Sorry. I don't really want to pull anyone

**Comment by DandyDev** [comment]
> Could you join forces? As a user of the theme development has been a little slow (totally understandable, I'm busy too)... but I also I don't like the idea of it splitting the project or migrating to a different theme.

To me, this seems the best solution as well. I was actually planning to setup a Gitter chat room for pelican-bootstrap3. This way, we could actually discuss progress. I'm perfectly willing to give write access to this repo to @lgiordani, but only if we can align on the goals for this theme :)

**Comment by cranmer** [comment]
I would encourage that with dev and master branches

**Comment by lgiordani** [comment]
@DandyDev you know that I'm here just to help (I already submitted and discussed PRs). I know that life is demanding and no one can do everything. Sorry again if what I did was perceived as an attempt to destroy something. If it helps you, I'm ready to give some time to the project. Obviously, given that this is your project, I'm not here to overturn it.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks again for your pull request! I appreciate the contribution, but I cannot accept this PR at the moment. It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your pull request there.

Sorry for the inconvenience!

**Pull request closed without merging**
